; KLC3: ISSUE DEFINE ERROR ERR_REGISTER_CHANGED "register(s) changed after calling your subroutine"
; KLC3: ISSUE DEFINE ERROR ERR_NOT_RETURN "your subroutine doesn't return to the autogenerated entry code" "You should not use HALT in your subroutine."
; KLC3: ISSUE SET_HINT WARN_HALT_IN_SUBROUTINE "Your subroutines are intended to be called multiple times. You should not halt in the subroutine."
; Output is checked by default
; KLC3: CHECK R0 to R7 for ERR_REGISTER_CHANGED DUMP_GOLD
; KLC3: CHECK LAST_INST for ERR_NOT_RETURN NOT_DUMP_GOLD
