; Test case generated by KLC3

; This file contains the test input event list.
; Note that this file may contains additional things after the end of event list.
; Please carefully identify the end of the event list.

.ORIG x4000

.FILL xFFFF	; EVENT1_WEEKDAY_BV

.STRINGZ "A"	; EVENT1_NAME

.FILL x0000	; EVENT1_SLOT

.FILL x0007	; EVENT2_WEEKDAY_BV

.STRINGZ "BBBBBBBBBB"	; EVENT2_NAME

.FILL x0000	; EVENT2_SLOT

.FILL x0003	; EVENT3_WEEKDAY_BV

.STRINGZ ""	; EVENT3_NAME

.FILL x0001	; EVENT3_SLOT

.FILL xFFFF

.END
