; Test case generated by KLC3

; Extra event input of the test case.
; Note that this file may contains additional things after the end of extra list.
; lease carefully identify the end of the extra list.

.ORIG x6000

.FILL x600A	; EXTRA1_NAME_PTR

.FILL x0000	; EXTRA1_WEEKDAY_BV

.FILL x8003	; EXTRA1_SLOT_BV

.FILL x600C	; EXTRA2_NAME_PTR

.FILL x000E	; EXTRA2_WEEKDAY_BV

.FILL x8003	; EXTRA2_SLOT_BV

.FILL x6017	; EXTRA3_NAME_PTR

.FILL x0018	; EXTRA3_WEEKDAY_BV

.FILL x0001	; EXTRA3_SLOT_BV

.FILL x0000

.STRINGZ "Z"	; EXTRA1_NAME

.STRINGZ "YYYYYYYYYY"	; EXTRA2_NAME

.STRINGZ "XXX"	; EXTRA3_NAME

.END
