; Test case generated by KLC3

; Event schedule input of the test case.
; Note that this file may contains additional things after the end of event list.
; Please carefully identify the end of the event list.

.ORIG x5000

.FILL x0041	; EVENT1_NAME_0

.FILL x0000	; EVENT1_NAME_1

.FILL x0000	; EVENT1_WEEKDAY_BV

.FILL x0000	; EVENT1_SLOT

.STRINGZ "BBBBBBBBBB"	; EVENT2_NAME

.FILL x0011	; EVENT2_WEEKDAY_BV

.FILL x0000	; EVENT2_SLOT

.STRINGZ ""

.END
